# Generated by Django 3.1 on 2020-08-07 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='instructions',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
