# Generated by Django 3.1 on 2020-09-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorties', to='recipebox_app.Article'),
        ),
    ]
