# Generated by Django 3.1 on 2020-08-07 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox_app', '0002_article_instructions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='post_date',
        ),
        migrations.AddField(
            model_name='article',
            name='time_required',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
